version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: todolist_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      vpcnet2:
        ipv4_address: 172.30.0.10

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    depends_on:
      - db
    ports:
      - 8000
    networks:
      vpcnet2:
        ipv4_address: 172.30.0.11

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "82:80"
    networks:
      vpcnet2:
        ipv4_address: 172.30.0.12

networks:
  vpcnet2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
